apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  name: enablealerts
  labels:
    codefresh.io/cert: enable-job  
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-phase: "PostSync"
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
