apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  name: grafana-notify-
  labels:
    codefresh.io/cert: grafana-job  
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-phase: "Sync"
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
